### ISSUE TITLE
xml配置

### ISSUE THREAD

**Issue by liuxianshengCn** [baomidou/dynamic-datasource-spring-boot-starter#14]
# Enviroment

JDK Version: 1.8

SpringBoot Version: 2.1.0

Starter Version:

# Describe

Expected Result: 
 
Actual Result:  

# Steps to reproduce

- Step 1 
`Caused by: org.apache.ibatis.exceptions.PersistenceException: `
`    Error querying database.  Cause: java.lang.NullPointerException`
 `   The error may exist in file [C:\usr\local\service\api\target\classes\mapper\TradeMapper.xml]`
`    The error may involve com.api.dao.TradeMapper.selectByPrimaryKey`
`    The error occurred while executing a query`
`    Cause: java.lang.NullPointerException`
`	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 37 more`
报这个错是什么原因

**Comment by liuxianshengCn** [comment]
@huayanYu 找到原因了，谢谢回复。
