### ISSUE TITLE
dbType not support : phoenix

### ISSUE THREAD

**Issue by RipleyGit** [baomidou/dynamic-datasource-spring-boot-starter#157]
# Enviroment
idea201903
JDK Version(required): 
jdk8
SpringBoot Version(required): 
2.0.6.RELEASE
Starter Version(required):
3.0.0
# Describe
Caused by: java.lang.IllegalStateException: dbType not support : phoenix, url jdbc:phoenix:dn3:2181
	at com.alibaba.druid.wall.WallFilter.init(WallFilter.java:167)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:839)
	at com.baomidou.dynamic.datasource.creator.DruidDataSourceCreator.createDataSource(DruidDataSourceCreator.java:140)
	at com.baomidou.dynamic.datasource.creator.DataSourceCreator.createDruidDataSource(DataSourceCreator.java:148)
	at com.baomidou.dynamic.datasource.creator.DataSourceCreator.createDataSource(DataSourceCreator.java:82)
	at com.baomidou.dynamic.datasource.provider.AbstractDataSourceProvider.createDataSourceMap(AbstractDataSourceProvider.java:44)
	at com.baomidou.dynamic.datasource.provider.YmlDynamicDataSourceProvider.loadDataSources(YmlDynamicDataSourceProvider.java:47)
	at com.baomidou.dynamic.datasource.DynamicRoutingDataSource.afterPropertiesSet(DynamicRoutingDataSource.java:226)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1753)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1690)
	... 103 more

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
请联系druid
