### ISSUE TITLE
Could not roll back JDBC transaction

### ISSUE THREAD

**Issue by 0532** [baomidou/dynamic-datasource-spring-boot-starter#239]
# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.1.5
dynamic-datasource-spring-boot-starter Version(required):
3.1.1
druid Version(optional):

# Describe
```
Caused by: org.springframework.transaction.TransactionSystemException: Could not roll back JDBC transaction; nested exception is java.sql.SQLException: Connection is closed
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doRollback(DataSourceTransactionManager.java:347)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:838)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:812)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.completeTransactionAfterThrowing(TransactionAspectSupport.java:552)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:299)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor.invoke(DynamicDataSourceAnnotationInterceptor.java:49)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
```

Expected Result: 

同一数据源下事务回滚

Actual Result:  
回滚失败

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
非本程序问题，建议检查数据库超时相关设置。
