### ISSUE TITLE
集成mybatis + shardingsphere 。 报错： Caused by: java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required

### ISSUE THREAD

**Issue by haochencheng** [baomidou/dynamic-datasource-spring-boot-starter#280]
[ INFO ] [2020-09-09 20:11:43.099] com.zaxxer.hikari.HikariDataSource [82] [main]- searchv3_2 - Start completed.
[ INFO ] [2020-09-09 20:11:43.101] com.baomidou.dynamic.datasource.DynamicRoutingDataSource [132] [main]- dynamic-datasource - load a datasource named [searchv3_2] success
[ INFO ] [2020-09-09 20:11:43.101] com.baomidou.dynamic.datasource.DynamicRoutingDataSource [132] [main]- dynamic-datasource - load a datasource named [search_item] success
[ INFO ] [2020-09-09 20:11:43.102] com.baomidou.dynamic.datasource.DynamicRoutingDataSource [237] [main]- dynamic-datasource initial loaded [2] datasource,primary datasource named [search_item]
[ INFO ] [2020-09-09 20:11:43.210] com.zaxxer.hikari.HikariDataSource [110] [main]- HikariPool-1 - Starting...
[ INFO ] [2020-09-09 20:11:43.215] com.zaxxer.hikari.HikariDataSource [123] [main]- HikariPool-1 - Start completed.
[ INFO ] [2020-09-09 20:11:43.242] com.zaxxer.hikari.HikariDataSource [110] [main]- HikariPool-2 - Starting...
[ INFO ] [2020-09-09 20:11:43.251] com.zaxxer.hikari.HikariDataSource [123] [main]- HikariPool-2 - Start completed.
[ INFO ] [2020-09-09 20:11:43.414] org.apache.shardingsphere.core.log.ConfigurationLogger [104] [main]- ShardingRuleConfiguration:
masterSlaveRules:
  ms_ds0:
    masterDataSourceName: master-0
    name: ms_ds0
    slaveDataSourceNames:
    - slave-0
tables:
  t_item:
    actualDataNodes: ms_ds0.t_item_${0..9}
    logicTable: t_item
    tableStrategy:
      complex:
        algorithmClassName: me.qury.search.item.config.ItemShardingAlgorithmConfig
        shardingColumns: app_package_id,query,country_code

[ INFO ] [2020-09-09 20:11:43.416] org.apache.shardingsphere.core.log.ConfigurationLogger [104] [main]- Properties:
sql.show: 'true'

[ INFO ] [2020-09-09 20:11:43.440] ShardingSphere-metadata [131] [main]- Loading 1 logic tables' meta data.
[ INFO ] [2020-09-09 20:11:43.516] ShardingSphere-metadata [70] [main]- Loading 16 tables' meta data.
[ INFO ] [2020-09-09 20:11:43.617] ShardingSphere-metadata [59] [main]- Meta data load finished, cost 201 milliseconds.
[ WARN ] [2020-09-09 20:11:43.661] org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext [559] [main]- Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kafkaReceiver': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'trainQueryAppServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'trainQueryAppMapper' defined in file [/Users/haochencheng/Workspace/qury/qury-search-item/target/classes/me/qury/search/item/mapper/TrainQueryAppMapper.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
[ INFO ] [2020-09-09 20:11:43.661] com.zaxxer.hikari.HikariDataSource [350] [main]- HikariPool-1 - Shutdown initiated...
[ INFO ] [2020-09-09 20:11:43.670] com.zaxxer.hikari.HikariDataSource [352] [main]- HikariPool-1 - Shutdown completed.
[ INFO ] [2020-09-09 20:11:43.670] com.zaxxer.hikari.HikariDataSource [350] [main]- HikariPool-2 - Shutdown initiated...
[ INFO ] [2020-09-09 20:11:43.675] com.zaxxer.hikari.HikariDataSource [352] [main]- HikariPool-2 - Shutdown completed.
[ INFO ] [2020-09-09 20:11:43.676] com.baomidou.dynamic.datasource.DynamicRoutingDataSource [217] [main]- dynamic-datasource start closing ....
[ INFO ] [2020-09-09 20:11:43.676] com.zaxxer.hikari.HikariDataSource [350] [main]- searchv3_2 - Shutdown initiated...
[ INFO ] [2020-09-09 20:11:43.682] com.zaxxer.hikari.HikariDataSource [352] [main]- searchv3_2 - Shutdown completed.
[ WARN ] [2020-09-09 20:11:43.683] org.springframework.beans.factory.support.DisposableBeanAdapter [267] [main]- Invocation of destroy method failed on bean with name 'dataSource': java.lang.NoSuchMethodException: com.sun.proxy.$Proxy143.close()
[ INFO ] [2020-09-09 20:11:43.686] org.apache.catalina.core.StandardService [173] [main]- Stopping service [Tomcat]
[ INFO ] [2020-09-09 20:11:43.712] org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener [136] [main]- 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ ERROR] [2020-09-09 20:11:43.735] org.springframework.boot.SpringApplication [837] [main]- Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kafkaReceiver': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'trainQueryAppServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'trainQueryAppMapper' defined in file [/Users/haochencheng/Workspace/qury/qury-search-item/target/classes/me/qury/search/item/mapper/TrainQueryAppMapper.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:321)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at me.qury.search.item.SearchItemApplication.main(SearchItemApplication.java:15)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'trainQueryAppServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'trainQueryAppMapper' defined in file [/Users/haochencheng/Workspace/qury/qury-search-item/target/classes/me/qury/search/item/mapper/TrainQueryAppMapper.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:321)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:521)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:497)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:650)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:239)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:318)
	... 18 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'trainQueryAppMapper' defined in file [/Users/haochencheng/Workspace/qury/qury-search-item/target/classes/me/qury/search/item/mapper/TrainQueryAppMapper.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeanByName(AbstractAutowireCapableBeanFactory.java:454)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:527)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:497)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:650)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:239)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:318)
	... 34 common frames omitted
Caused by: java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
	at org.springframework.util.Assert.notNull(Assert.java:198)
	at org.mybatis.spring.support.SqlSessionDaoSupport.checkDaoConfig(SqlSessionDaoSupport.java:122)
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:73)
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	... 47 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:60127', transport: 'socket'

Process finished with exit code 1

参考 https://github.com/baomidou/dynamic-datasource-spring-boot-starter/wiki/Integration-With-ShardingJdbc
配置

依赖版本
```

        <mybatis-plus.version>3.4.0</mybatis-plus.version>
        <sharding-sphere.version>4.1.1</sharding-sphere.version>


<dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>1.3.0</version>
        </dependency>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
            <version>3.2.0</version>
        </dependency>
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>${mybatis-plus.version}</version>
        </dependency>

        <!-- 分库分表-->
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>${sharding-sphere.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-core-common</artifactId>
            <version>${sharding-sphere.version}</version>
        </dependency>
        <!-- 分库分表 end-->
```

**Comment by haochencheng** [comment]
@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})

没集成动态数据源 之前，正常启动运行。集成后报错 。

**Comment by huayanYu** [comment]
你能使用示例项目复现吗？ 如果可以请fork下来给我一个地址。

**Comment by haochencheng** [comment]
> 你能使用示例项目复现吗？ 如果可以请fork下来给我一个地址。

感谢回复。
https://github.com/haochencheng/dynamic-datasource-spring-boot-starter.git

![image](https://user-images.githubusercontent.com/20943919/92680526-9ecd8a80-f35d-11ea-9afe-f1cdfbee0d32.png)

复现项目 是 mybatisplus3-sample

项目中使用的 sql 在 db/test.sql中 

使用这个示例项目启动 会报上面的错误。

**Comment by haochencheng** [comment]
解决了  MybatisAutoConfiguration 在 一个 DataSource 或者多个DataSource设置了 Primary 才会自动装配。
![image](https://user-images.githubusercontent.com/20943919/92685541-7ef09380-f36a-11ea-9a2a-4bb119cc0ce9.png)

我之前没有 动态 数据源 没有 配置 @Primary 导致 mybatis 没有自动装配。
![image](https://user-images.githubusercontent.com/20943919/92685647-c24b0200-f36a-11ea-8077-d8f0cabf3351.png)
