### ISSUE TITLE
java.lang.NoSuchMethodException: com.p6spy.engine.spy.P6DataSource.close()

### ISSUE THREAD

**Issue by Dupenn** [baomidou/dynamic-datasource-spring-boot-starter#39]
maven dependency：
```xml
<dependency>
  <groupId>p6spy</groupId>
  <artifactId>p6spy</artifactId>
  <version>3.8.2</version>
</dependency>
<dependency>
  <groupId>com.baomidou</groupId>
  <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
  <version>2.5.3</version>
</dependency>
```
error message:
```java
java.lang.NoSuchMethodException: com.p6spy.engine.spy.P6DataSource.close()
  at java.lang.Class.getDeclaredMethod(Class.java:2130)
  at com.baomidou.dynamic.datasource.DynamicRoutingDataSource.destroy(DynamicRoutingDataSource.java:179)
  at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:256)
  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571)
  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543)
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1052)
  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504)
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1059)
  at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1035)
  at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1011)
  at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:931)
```
查询正常，日志也正常打印，但是程序结束的时候打印了这个异常

**Comment by huayanYu** [comment]
下个版本修复
