### ISSUE TITLE
使用 @Autowire注入 Spring，  DynamicRoutingDataSource 报错NoSuchBeanDefinitionException 

### ISSUE THREAD

**Issue by justime** [baomidou/dynamic-datasource-spring-boot-starter#412]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment                         

JDK Version(required):  1.8

SpringBoot Version(required):    2.3.2

dynamic-datasource-spring-boot-starter Version(required):      2.5.8 和 3.3.2 都是试了

druid Version(optional):  no use

# Describe what happened

Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.baomidou.dynamic.datasource.DynamicRoutingDataSource' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1717)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1273)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884)
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
... 19 common frames omitted

把 SpringBoot版本换成 2.2.5 就行了。   

想问下是还没适配SpringBoot2.3.X版吗？

**Comment by huayanYu** [comment]
注入DataSource
