### ISSUE TITLE
dynamic-datasource-spring-boot-starter-4.0.0-B1 升级报错

### ISSUE THREAD

**Issue by afish177** [baomidou/dynamic-datasource-spring-boot-starter#508]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.7.12

dynamic-datasource-spring-boot-starter Version(required): 4.0.0-B1

druid Version(optional): 1.2.18

# Describe what happened

启动报错
之前 版本是dynamic-datasource-spring-boot-starter-3.6.1
druid 1.2.16
无误 这是能正常运行启动得 
![image](https://github.com/baomidou/dynamic-datasource-spring-boot-starter/assets/32056262/8d0e0be7-844c-4195-a875-0ddc3e07f4f1)

Expected Result:

Actual Result:
![image](https://github.com/baomidou/dynamic-datasource-spring-boot-starter/assets/32056262/6e20c0ba-a219-4d7a-8ebf-e168fce0f950)

If there is an exception,or aop invalid,please attach the exception trace:

```
java.lang.ArrayStoreException: null
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:602)
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:600)
	at java.lang.reflect.Executable.getDeclaredAnnotations(Executable.java:588)
	at java.lang.reflect.Method.getDeclaredAnnotations(Method.java:630)
	at org.springframework.core.annotation.AnnotationsScanner.getDeclaredAnnotations(AnnotationsScanner.java:454)
	at org.springframework.core.annotation.AnnotationsScanner.isKnownEmpty(AnnotationsScanner.java:492)
	at org.springframework.core.annotation.TypeMappedAnnotations.from(TypeMappedAnnotations.java:251)
	at org.springframework.core.annotation.MergedAnnotations.from(MergedAnnotations.java:351)
	at org.springframework.core.annotation.MergedAnnotations.from(MergedAnnotations.java:330)
	at org.springframework.core.annotation.AnnotatedElementUtils.findAnnotations(AnnotatedElementUtils.java:800)
	at org.springframework.core.annotation.AnnotatedElementUtils.hasAnnotation(AnnotatedElementUtils.java:541)
	at org.springframework.context.annotation.BeanAnnotationHelper.isBeanAnnotated(BeanAnnotationHelper.java:41)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.isMatch(ConfigurationClassEnhancer.java:407)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$ConditionalCallbackFilter.accept(ConfigurationClassEnhancer.java:192)
	at org.springframework.cglib.proxy.Enhancer.emitMethods(Enhancer.java:1217)
	at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:726)
	at org.springframework.cglib.transform.TransformingClassGenerator.generateClass(TransformingClassGenerator.java:33)
	at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.springframework.cglib.core.ClassLoaderAwareGeneratorStrategy.generate(ClassLoaderAwareGeneratorStrategy.java:57)
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
确实没法复现....,你能提交个最小化能复现的项目么

**Comment by afish177** [comment]
我试试看 稍等
&nbsp;


浮生ふ物语
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月15日(星期四) 下午3:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [baomidou/dynamic-datasource-spring-boot-starter] dynamic-datasource-spring-boot-starter-4.0.0-B1 升级报错 (Issue #508)





 
确实没法复现....,你能提交个最小化能复现的项目么

**Comment by afish177** [comment]
这就是最小化 复现了
一个是可运行 老版本&nbsp; 一个是升级后得 麻烦大佬看看了
感谢大佬




浮生ふ物语
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "baomidou/dynamic-datasource-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月15日(星期四) 下午3:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/dynamic-datasource-spring-boot-starter] dynamic-datasource-spring-boot-starter-4.0.0-B1 升级报错 (Issue #508)





 
确实没法复现....,你能提交个最小化能复现的项目么

**Comment by afish177** [comment]
> 确实没法复现....,你能提交个最小化能复现的项目么

[](url)

> 确实没法复现....,你能提交个最小化能复现的项目么

邮箱已发送 辛苦大佬看看了

**Comment by huayanYu** [comment]
发哪去了,没收到

**Comment by afish177** [comment]
大佬给个邮箱 我好发送 我是直接回复 发得
&nbsp;


浮生ふ物语
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月16日(星期五) 上午10:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [baomidou/dynamic-datasource-spring-boot-starter] dynamic-datasource-spring-boot-starter-4.0.0-B1 升级报错 (Issue #508)





 
发哪去了,没收到

**Comment by huayanYu** [comment]
tracy5546@gmail.com

**Comment by afish177** [comment]
已发送 谢谢大佬
&nbsp;


浮生ふ物语
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月16日(星期五) 上午10:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [baomidou/dynamic-datasource-spring-boot-starter] dynamic-datasource-spring-boot-starter-4.0.0-B1 升级报错 (Issue #508)





 
***@***.***
 
&mdash;

**Comment by huayanYu** [comment]
兄弟,你是不是没理解最小化复现demo

**Comment by afish177** [comment]
。。。 我这个是项目 我自己剥离 最简单得了 再小 真的不能了&nbsp;


浮生ふ物语
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月16日(星期五) 上午10:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [baomidou/dynamic-datasource-spring-boot-starter] dynamic-datasource-spring-boot-starter-4.0.0-B1 升级报错 (Issue #508)





 
兄弟,你是不是没理解最小化复现demo

**Comment by huayanYu** [comment]
抱歉了,建议不要升级...
